cmake_minimum_required(VERSION 3.5)
project(teensy-audio-launch-ctrl)
include(cmake/cmake_declare_and_fetch.cmake.in)
set(CMAKE_CXX_STANDARD 17)

if (NOT DEFINED TEENSY_VERSION)
    set(BUILD_FOR_LINUX 1)
    add_definitions(-DBUILD_FOR_LINUX)
endif()

if (NOT DEFINED BUILD_FOR_LINUX)
    set(CMAKE_EXE_LINKER_FLAGS "--specs=nano.specs" CACHE INTERNAL "")

    DeclareAndFetchNoSource(teensy_cmake_macros            https://github.com/newdigate/teensy-cmake-macros.git main)
    include(${teensy_cmake_macros_SOURCE_DIR}/CMakeLists.include.txt)
    import_arduino_library(cores ${teensy_cores_SOURCE_DIR}/teensy4 avr debug util)

    import_arduino_library_git(SPI https://github.com/PaulStoffregen/SPI.git master "")
    import_arduino_library_git(SdFat https://github.com/PaulStoffregen/SdFat.git master "src" common DigitalIO ExFatLib FatLib FsLib iostream SdCard SpiDriver)
    import_arduino_library_git(SD https://github.com/PaulStoffregen/SD.git Juse_Use_SdFat src)
    import_arduino_library_git(Encoder https://github.com/PaulStoffregen/Encoder.git master "")
    import_arduino_library_git(Bounce2 https://github.com/PaulStoffregen/Bounce2.git master src)
    import_arduino_library_git(SerialFlash https://github.com/PaulStoffregen/SerialFlash.git master "" util)
    import_arduino_library_git(Wire https://github.com/PaulStoffregen/Wire.git master "" utility)
    import_arduino_library_git(arm_math https://github.com/PaulStoffregen/arm_math.git master src)
    import_arduino_library_git(ST7735_t3 https://github.com/PaulStoffregen/ST7735_t3.git master "")
    import_arduino_library_git(TeensyGFX https://github.com/newdigate/teensy-gfx.git main src)
    import_arduino_library_git(TeensyGFXControls https://github.com/newdigate/teensy-gfx-controls.git main src)
    import_arduino_library_git(rgb565_colors https://github.com/newdigate/rgb565_colors.git noinstall src)
    import_arduino_library_git(MIDI https://github.com/PaulStoffregen/MIDI master src)
    import_arduino_library_git(Audio https://github.com/PaulStoffregen/Audio master src utility)
    import_arduino_library_git(teensy_variable_playback https://github.com/newdigate/teensy-variable-playback master src)
    import_arduino_library_git(USBHost_t36 https://github.com/PaulStoffregen/USBHost_t36 master "/" utility)
    add_subdirectory(src)
    add_subdirectory(examples)
else()
    DeclareAndFetch(teensy_x86_stubs            https://github.com/newdigate/teensy-x86-stubs.git main src)
    DeclareAndFetch(teensy_x86_sd_stubs         https://github.com/newdigate/teensy-x86-sd-stubs main src)
    DeclareAndFetch(teensy_x86_encoder_stubs    https://github.com/newdigate/teensy-x86-encoder-stubs.git main src)
    DeclareAndFetch(teensy_x86_bounce2_stubs    https://github.com/newdigate/teensy-x86-bounce2-stubs.git main src)
    DeclareAndFetch(teensy_audio_x86_stubs      https://github.com/newdigate/teensy-audio-x86-stubs main "src extras/soundio/src")
    DeclareAndFetch(rtmidi                      https://github.com/thestk/rtmidi.git master "/")
    DeclareAndFetch(teensy_x86_midi_stubs       https://github.com/newdigate/teensy-x86-midi-stubs.git main "src extras/rtmidi/src")
    DeclareAndFetch(teensy_gfx                  https://github.com/newdigate/teensy-gfx.git main src)
    DeclareAndFetch(teensy_st7735_linux_stubs   https://github.com/newdigate/teensy-st7735-linux-stubs.git main "src extras/opengl/src")
    DeclareAndFetch(teensy_gfx_controls         https://github.com/newdigate/teensy-gfx-controls.git main src)
    DeclareAndFetch(teensy_variable_playback    https://github.com/newdigate/teensy-variable-playback master src)
    DeclareAndFetch(teensy_polyphony            https://github.com/newdigate/teensy-polyphony main src)
    DeclareAndFetch(arduino_tftpianoview        https://github.com/newdigate/arduino-tftpianoview master src)

    add_subdirectory(src)
    #add_subdirectory(extras/ILI9341_t3_controls)
    #add_subdirectory(extras/ILI9341_t3_Menu)
    #add_subdirectory(extras/ArduinoMenu/src)
    #add_subdirectory(extras/controls_example)
    #add_subdirectory(extras/menu_example)
    #add_subdirectory(extras/menu_example2)
    #add_subdirectory(extras/sd_menu_example)
    #add_subdirectory(extras/sample_launcher)
    #add_subdirectory(extras/scenecontroller/src)
    #add_subdirectory(extras/scenecontroller/examples/scene_menus)
    include(extras/opengl.cmake)
    add_subdirectory(extras/sampler)
    #add_subdirectory(extras/teensy_controls/src)
    #add_subdirectory(extras/teensy_controls/examples/view_example)
    #add_subdirectory(extras/teensy_controls/examples/basic)
    #add_subdirectory(test)
endif()